version: '2.1'

orbs:
  slack: circleci/slack@3.4.2

executors:
  shopizer-ci:
    docker:
      - image: shopizerecomm/ci:java17
        auth:
          username: shopizerecomm
          password: $DOCKERHUB_PASSWORD
      
working_directory: /tmp

jobs:
  setup:
    executor: shopizer-ci
    steps:
      - checkout
      - run:
          name: Set up JDK 17
          command: |
            sdk install java 17.0.6-zulu
            java -version
  lint:
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "Running lint checks"
      - run:
          name: Lint check
          command: mvn checkstyle:check
  test:
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "Running unit tests"
      - run: mvn test
  build:
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "Building the project"
      - run: mvn clean install
  deploy:
    machine: true
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Deploy to Docker
          command: |
            docker login -u shopizerecomm -p $DOCKERHUB_PASSWORD
            (cd sm-shop && docker build . -t shopizerecomm/shopizer:latest)
            docker push shopizerecomm/shopizer:latest
  sast:
    executor: shopizer-ci
    steps:
      - checkout
      - run: echo "Running SAST"
      - run: mvn sonar:sonar

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - lint
      - test
      - build
      - sast:
          requires:
            - build
      - deploy:
          requires:
            - build